// <auto-generated />
namespace n01629177_passion_project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class pricetableaddfieldstypeunitprice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pricetableaddfieldstypeunitprice));
        
        string IMigrationMetadata.Id
        {
            get { return "202402191826238_price-table-add-fields-type-unitprice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
