// <auto-generated />
namespace n01629177_passion_project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addbasepricerecords : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addbasepricerecords));
        
        string IMigrationMetadata.Id
        {
            get { return "202402050156183_add-base-price-records"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
